<a href="https://colab.research.google.com/github/mukulre/Projects/blob/main/E0322052_Data_Science_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data={
    'Name':['John','Emma','Sam','Lisa','Tom'],
    'Age':[25,30,28,22,35],
    'Country':['USA','Canada','Australia','UK','Germany'],
    'Salary':[50000,60000,55000,52000,65000]
}
df=pd.DataFrame(data)
print("Original Dataframe:")
print(df)

Original Dataframe:
   Name  Age    Country  Salary
0  John   25        USA   50000
1  Emma   30     Canada   60000
2   Sam   28  Australia   55000
3  Lisa   22         UK   52000
4   Tom   35    Germany   65000


In [ ]:
name_age=df[['Name','Age']]
print("\nSelecting columns(Name and Age columns):")
print(name_age)


Selecting columns(Name and Age columns):
   Name  Age
0  John   25
1  Emma   30
2   Sam   28
3  Lisa   22
4   Tom   35


In [ ]:
filtered_df=df[df['Country']=='USA']
print("\nFiltered Dataframe(Country='USA'):")
print(filtered_df)


Filtered Dataframe(Country='USA'):
   Name  Age Country  Salary
0  John   25     USA   50000


In [ ]:
sorted_df=df.sort_values(by='Salary',ascending=False)
print("\nSorted Dataframe(Salary in descending order):")
print(sorted_df)


Sorted Dataframe(Salary in descending order):
   Name  Age    Country  Salary
4   Tom   35    Germany   65000
1  Emma   30     Canada   60000
2   Sam   28  Australia   55000
3  Lisa   22         UK   52000
0  John   25        USA   50000


In [ ]:
print("\nAggregating data (Salary):")
average_salary=df['Salary'].mean()
print("\nAverage Salary:",average_salary)


Aggregating data (Salary):

Average Salary: 56400.0


In [ ]:
Experience=df['Experience']=[3,6,4,8,5]
print("\nDataframe with aded Experience column:")
print(df)


Dataframe with aded Experience column:
   Name  Age    Country  Salary  Experience
0  John   25        USA   50000           3
1  Emma   30     Canada   60000           6
2   Sam   28  Australia   55000           4
3  Lisa   22         UK   52000           8
4   Tom   35    Germany   65000           5


In [ ]:
df.loc[df['Name']=='Emma','Salary']=65000
print("\nDataframe after updating Emma's Salary:")
print(df)


Dataframe after updating Emma's Salary:
   Name  Age    Country  Salary  Experience
0  John   25        USA   50000           3
1  Emma   30     Canada   65000           6
2   Sam   28  Australia   55000           4
3  Lisa   22         UK   52000           8
4   Tom   35    Germany   65000           5


In [ ]:
df=df.drop('Experience',axis=1)
print("\nDataframe after dropping the Experience column:")
print(df)


Dataframe after dropping the Experience column:
   Name  Age    Country  Salary
0  John   25        USA   50000
1  Emma   30     Canada   65000
2   Sam   28  Australia   55000
3  Lisa   22         UK   52000
4   Tom   35    Germany   65000


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv('/content/Data (3).csv')
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 nan -1.0182239953527132]
 [0.0 1.0 0.0 -0.038910211282047996 nan]
 [1.0 0.0 0.0 0.5058327466666259 0.583476671494251]
 [0.0 0.0 1.0 -0.3112816902563849 -0.2974586952715793]
 [0.0 0.0 1.0 -1.809324824615238 -1.3385641287221062]
 [1.0 0.0 0.0 1.0505757046152997 1.1440719048906884]
 [0.0 1.0 0.0 1.3229471835896367 1.4644120382600814]
 [1.0 0.0 0.0 -0.7198389087178904 -0.537713795298624]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.4007676061537326 -0.8580539286680168]
 [1.0 0.0 0.0 -0.4474674297435534 0.18305150478250995]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]
