<a href="https://colab.research.google.com/github/mukulre/Projects/blob/main/How_to_Save_a_Machine_Learning_Model%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("student-mat.csv")

data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]

predict = "G3"
x = np.array(data.drop([predict], axis=1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)

import pickle
with open("pickle_model", "wb") as file:
    pickle.dump(linear_regression, file)

with open("pickle_model", "rb") as file:
    model = pickle.load(file)

predictions = model.predict(xtest)

for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 9.4106602   9.24845646  3.69411057 19.2915031   9.24845646]
 [ 9.4106602   9.4106602   3.69411057 19.2915031  12.88981184]
 [ 5.97271079  8.06119722  3.69411057  7.94332614 12.5089432 ]
 ...
 [12.5089432   8.06119722 12.8741305   7.94332614  7.94332614]
 [18.42276662 13.96825082 12.8741305  19.2915031  19.2915031 ]
 [ 8.06119722  8.27664515 12.8741305  19.2915031   9.4106602 ]] [[[ 9 10  2  0  4]
  [ 8 10  2  0  4]
  [ 6  5  1  2  0]
  [19 19  4  0  4]
  [ 8 10  2  0  4]]

 [[ 9 10  2  0  4]
  [ 9 10  2  0  4]
  [ 6  5  1  2  0]
  [19 19  4  0  4]
  [12 13  1  1  6]]

 [[ 7  6  2  0 26]
  [ 9  9  2  1  0]
  [ 6  5  1  2  0]
  [10  8  1  0  6]
  [14 13  4  0  0]]

 ...

 [[14 13  4  0  0]
  [ 9  9  2  1  0]
  [16 12  1  0  8]
  [10  8  1  0  6]
  [10  8  1  0  6]]

 [[19 18  3  0  0]
  [14 14  2  0  0]
  [16 12  1  0  8]
  [19 19  4  0  4]
  [19 19  4  0  4]]

 [[ 9  9  2  1  0]
  [ 8  9  2  0  4]
  [16 12  1  0  8]
  [19 19  4  0  4]
  [ 9 10  2  0  4]]] [array([[10, 10,  0, 20, 10]