<a href="https://colab.research.google.com/github/mukulre/Projects/blob/main/MUKUL_RAJ_(e0322052)_featureselectionandmodelbuilding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import packages
import numpy as np # NumPy is a Python package that stands for ‘Numerical Python’. It is the core library for scientific computing
import pandas as pd # Pandas is used for data manipulation, analysis and cleaning.
import matplotlib.pyplot as plt # powerful plotting library for python that offers a varied spectrum of 1D, 2D, and 3D visualizations.
from IPython.display import display, HTML, display_html # Display the HTML representation of an object.
import seaborn as sns # Seaborn is a data visualization library in Python based on matplotlib


In [ ]:
from pandas import read_csv #  imports a CSV file to DataFrame format.
# Load the dataset
data = pd.read_csv('diabetesafterpreprocessing.csv')

In [ ]:
data

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0     58       1         0           0                   0         1   
1     41       1         1           0                   0         1   
2     45       1         0           0                   1         1   
3     57       1         1           1                   0         1   
4     66       1         1           1                   1         1   
..   ...     ...       ...         ...                 ...       ...   
201   54       0         1           1                   1         1   
202   39       0         1           1                   1         0   
203   48       0         1           1                   1         1   
204   32       0         0           0                   0         1   
205   42       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                1        0             0   
1             1               0                0        1             0   
2             1               1                0        1             0   
3             1               1                0        0             0   
4             0               0                1        1             1   
..          ...             ...              ...      ...           ...   
201           1               0                0        0             0   
202           1               0                0        1             0   
203           1               0                0        1             1   
204           0               0                1        1             0   
205           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                  0                1                 0         1        0   
1                  1                0                 1         1        0   
2                  1                0                 0         0        0   
3                  1                1                 0         0        0   
4                  0                1                 1         0        0   
..               ...              ...               ...       ...      ...   
201                0                1                 0         0        0   
202                1                1                 0         0        0   
203                1                1                 0         0        0   
204                1                0                 0         1        0   
205                0                0                 0         0        0   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
201      1  
202      1  
203      1  
204      0  
205      0  

[206 rows x 17 columns]

In [ ]:
!pip install sweetviz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 15.0 MB/s eta 0:00:00


In [ ]:
import sweetviz as sv
sweet_report = sv.analyze(data)
sweet_report.show_html('sweet_report_diabetes.html')

                                             |          | [  0%]   00:00 -> (? left)

Report sweet_report_diabetes.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


In [ ]:
!pip install ydata-profiling

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.9/390.9 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 22.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 28.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 14.2 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=7ea205d2ff968d7234627f6233ff2193c155b736c91581b8b206670261900cc3
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin


In [ ]:
import ydata_profiling as yd
profile = yd.ProfileReport(data)
profile.to_file("output.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
%matplotlib inline

In [ ]:
!pip install autoviz
from autoviz.AutoViz_Class import AutoViz_Class
import pandas as pd
from autoviz.AutoViz_Class import AutoViz_Class

# Instantiate the AutoViz class
AV = AutoViz_Class()

# Generate and display plots
dft = AV.AutoViz(
    filename="",  # No file path because we're using a DataFrame
    sep=",",  # Separator used in the file; irrelevant for DataFrame
    depVar="class",  # Dependent variable
    dfte=data,  # DataFrame to analyze
    header=0,  # Header row index
    verbose=2,  # Verbose level for details
    lowess=False,  # Disable lowess smoothing
    chart_format="svg",  # Plot format
    max_rows_analyzed=500,  # Maximum rows to analyze
    max_cols_analyzed=20,  # Maximum columns to analyze
    save_plot_dir=None  # Inline plots; no saving
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.5/67.5 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.9/161.9 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.9/255.9 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 22.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 30.0 MB/s eta 0:00:00
  Attempting uninstall: xgboost
    Found existing installation: xgboost 2.1.3
    Uninstalling xgboost-2.1.3:
      Successfully uninstalled xgboost-2.1.3
Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)
Shape of your Data Set loaded: (206, 17)
#######################################################################################
###############

All Plots are saved in ./AutoViz_Plots/class
Time to run AutoViz = 6 seconds 


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, mutual_info_classif, RFE
from sklearn.metrics import accuracy_score

# Load the dataset
data = pd.read_csv('diabetesafterpreprocessing.csv')

# Separate features and target
X = data.drop(columns=['class'])  # Features
y = data['class']  # Target variable

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Filter-Based Feature Selection
best_features = SelectKBest(score_func=mutual_info_classif, k='all')  # Initialize selector
best_features.fit(X_train, y_train)  # Fit to training data
scores = best_features.scores_  # Get feature scores

# Select top features based on threshold (e.g., median score)
threshold = np.median(scores)  # Calculate threshold
selected_features_filter = [feature for score, feature in zip(scores, X.columns) if score >= threshold]  # Filter features
print(f"Selected features (Filter-Based): {selected_features_filter}")

# Subset data based on selected features
X_train_filter = X_train[selected_features_filter]  # Filter training data
X_test_filter = X_test[selected_features_filter]  # Filter testing data

# Wrapper-Based Feature Selection
model = RandomForestClassifier(random_state=42)  # Initialize model
rfe = RFE(estimator=model)  # Initialize RFE
rfe.fit(X_train, y_train)  # Fit RFE to training data
selected_features_wrapper = X_train.columns[rfe.support_].tolist()  # Get selected features
print(f"Selected features (Wrapper-Based): {selected_features_wrapper}")

# Subset data based on selected features
X_train_wrapper = X_train[selected_features_wrapper]  # Wrapper-selected training data
X_test_wrapper = X_test[selected_features_wrapper]  # Wrapper-selected testing data

# Evaluate models on selected features
# Filter-Based Evaluation
model.fit(X_train_filter, y_train)  # Train model on filter-selected features
y_pred_filter = model.predict(X_test_filter)  # Predict on test data
accuracy_filter = accuracy_score(y_test, y_pred_filter)  # Calculate accuracy
print(f"Accuracy with Filter-Based Features: {accuracy_filter}")

# Wrapper-Based Evaluation
model.fit(X_train_wrapper, y_train)  # Train model on wrapper-selected features
y_pred_wrapper = model.predict(X_test_wrapper)  # Predict on test data
accuracy_wrapper = accuracy_score(y_test, y_pred_wrapper)  # Calculate accuracy
print(f"Accuracy with Wrapper-Based Features: {accuracy_wrapper}")



Selected features (Filter-Based): ['Polyuria', 'Polydipsia', 'sudden weight loss', 'visual blurring', 'Irritability', 'partial paresis', 'muscle stiffness', 'Obesity']
Selected features (Wrapper-Based): ['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'Itching', 'partial paresis', 'Alopecia']
Accuracy with Filter-Based Features: 0.8571428571428571
Accuracy with Wrapper-Based Features: 0.8809523809523809


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=42)
X_train.shape

(164, 16)

In [ ]:
# Recursive feature elimination with cross validation (RFECV) and random forest classification
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestClassifier

clf_rf_4 = RandomForestClassifier(random_state=42)
rfecv = RFECV(estimator=clf_rf_4, step=1, cv=10,scoring='accuracy')   #5-fold cross-validation
rfecv = rfecv.fit(X_train, y_train)

print('Optimal number of features :', rfecv.n_features_)

# Get the original feature names from 'X' (DataFrame) before scaling
original_feature_names = X.columns

# Use original_feature_names to get the selected feature names
print('Best features :', list(original_feature_names[rfecv.support_]))

Optimal number of features : 15
Best features : ['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching', 'Irritability', 'delayed healing', 'partial paresis', 'muscle stiffness', 'Alopecia']


In [ ]:
data.drop('Obesity',axis = 1,inplace = True) # dropping of the "Obesity" feature from the dataset

In [ ]:
data.shape

(206, 16)

In [ ]:
data.to_csv("diabetesafterdropping.csv", index = False) # Modifying the dataset after dropping "Obesity" feature

In [ ]:
data = pd.read_csv('diabetesafterdropping.csv')

In [ ]:
# Separate features and target
X1 = data.drop(columns=['class'])  # Features
y1 = data['class']  # Target variable

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X1,y1,test_size = 0.2,random_state=42)
X_train.shape

(164, 15)

In [ ]:
# Building of Logistic Regression Model
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
lg.fit(X_train,y_train)

LogisticRegression()

In [ ]:
# Predicting the values of X_test
y_pred = lg.predict(X_test)

In [ ]:
# Generation of confusion matrix and classification report with accuracy, precsion, recall, f1-score and support
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14  3]
 [ 4 21]]
              precision    recall  f1-score   support

           0       0.78      0.82      0.80        17
           1       0.88      0.84      0.86        25

    accuracy                           0.83        42
   macro avg       0.83      0.83      0.83        42
weighted avg       0.84      0.83      0.83        42



In [ ]:
cmlg=confusion_matrix(y_test, y_pred)

In [ ]:
f, ax=plt.subplots(figsize=(5,5))
sns.heatmap(cmlg,annot=True,linewidths=0.5,linecolor="red",fmt=".0f",ax=ax)
plt.xlabel("y_pred")
plt.ylabel("y_test")
plt.show()

In [ ]:
# Building of Logistic Regression Model
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression(C=1.0, penalty='l2', solver='liblinear', class_weight='balanced', max_iter=500)
lg.fit(X_train,y_train)

LogisticRegression(class_weight='balanced', max_iter=500, solver='liblinear')

In [ ]:
# Predicting the values of X_test
y_pred = lg.predict(X_test)

In [ ]:
# Generation of confusion matrix and classification report with accuracy, precsion, recall, f1-score and support
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[15  2]
 [ 4 21]]
              precision    recall  f1-score   support

           0       0.79      0.88      0.83        17
           1       0.91      0.84      0.88        25

    accuracy                           0.86        42
   macro avg       0.85      0.86      0.85        42
weighted avg       0.86      0.86      0.86        42



In [ ]:
cmlg=confusion_matrix(y_test, y_pred)

In [ ]:
f, ax=plt.subplots(figsize=(5,5))
sns.heatmap(cmlg,annot=True,linewidths=0.5,linecolor="red",fmt=".0f",ax=ax)
plt.xlabel("y_pred")
plt.ylabel("y_test")
plt.show()

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[11  6]
 [ 7 18]]
              precision    recall  f1-score   support

           0       0.61      0.65      0.63        17
           1       0.75      0.72      0.73        25

    accuracy                           0.69        42
   macro avg       0.68      0.68      0.68        42
weighted avg       0.69      0.69      0.69        42



In [ ]:
cmknn=confusion_matrix(y_test, y_pred)

In [ ]:
f, ax=plt.subplots(figsize=(5,5))
sns.heatmap(cmknn,annot=True,linewidths=0.5,linecolor="red",fmt=".0f",ax=ax)
plt.xlabel("y_pred")
plt.ylabel("y_test")
plt.show()

In [ ]:
from sklearn import svm
svm_classifier = svm.SVC(kernel='linear')
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_predict = svm_classifier.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[14  3]
 [ 4 21]]
              precision    recall  f1-score   support

           0       0.78      0.82      0.80        17
           1       0.88      0.84      0.86        25

    accuracy                           0.83        42
   macro avg       0.83      0.83      0.83        42
weighted avg       0.84      0.83      0.83        42



In [ ]:
from sklearn import svm
svm_classifier = svm.SVC(kernel='rbf')
svm_classifier.fit(X_train, y_train)

SVC()

In [ ]:
y_predict = svm_classifier.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[ 0 17]
 [ 0 25]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           1       0.60      1.00      0.75        25

    accuracy                           0.60        42
   macro avg       0.30      0.50      0.37        42
weighted avg       0.35      0.60      0.44        42

