<a href="https://colab.research.google.com/github/mukulre/Projects/blob/main/Student_Grades_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [3]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], axis=1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [4]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.7593086579009716


In [5]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[10.77974059 13.2439828   5.00273718  6.1424059  13.2439828 ]
 [10.77974059 10.77974059  5.00273718  6.1424059  12.65539585]
 [ 7.87318029  8.3354406   5.00273718  9.5453061  13.13770333]
 ...
 [13.13770333  8.3354406   8.26944556  9.5453061   9.5453061 ]
 [11.60911581 12.0370015   8.26944556  6.1424059   6.1424059 ]
 [ 8.3354406   6.4520734   8.26944556  6.1424059  10.77974059]] [[[11 11  1  0  0]
  [15 14  3  2  4]
  [ 7  7  2  3  5]
  [ 7  8  2  3 10]
  [15 14  3  2  4]]

 [[11 11  1  0  0]
  [11 11  1  0  0]
  [ 7  7  2  3  5]
  [ 7  8  2  3 10]
  [14 13  4  0  0]]

 [[ 9  9  2  2 11]
  [ 8  9  2  0  4]
  [ 7  7  2  3  5]
  [10 10  2  0  2]
  [14 13  2  0  4]]

 ...

 [[14 13  2  0  4]
  [ 8  9  2  0  4]
  [ 8  9  2  0  2]
  [10 10  2  0  2]
  [10 10  2  0  2]]

 [[14 12  2  1  0]
  [12 12  1  0  4]
  [ 8  9  2  0  2]
  [ 7  8  2  3 10]
  [ 7  8  2  3 10]]

 [[ 8  9  2  0  4]
  [ 8  7  2  0  6]
  [ 8  9  2  0  2]
  [ 7  8  2  3 10]
  [11 11  1  0  0]]] [array([[10, 15,  7, 10, 15]